# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push (A push gets triggered also when a Pull Request is merged)
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
    - 'Book/**'
    - '.github/workflows/CI.yml'

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    
    # pip install furo
    # OR
    # git clone https://github.com/QuantEcon/quantecon-book-theme.git
    # cd quantecon-book-theme
    # python setup.py install
    # cd ..
    - name: Install new book theme
      run: |
        git clone https://github.com/executablebooks/sphinx-book-theme.git
        cd sphinx-book-theme
        python setup.py install
        cd ..
    
    - name: Install dependencies
      run: |
        sudo apt-get install python3-pip
        pip install jupyter-book
        PATH="${PATH}:${HOME}/.local/bin"
        jupyter-book --version
    # Build the book
    - name: Build the book
      run: |
        jupyter-book build --all ./Book
    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ./Book/_build/html/
